@node ANVL erlc
@chapter Builtin Plugin anvl_erlc

@code{anvl_erlc} is a built-in plugin that compiles Erlang applications structured accorging to the
@url{https://www.erlang.org/doc/system/applications#directory-structure,OTP design principles}.
It allows ANVL to load other 3rd-party plugins.

@macro erlang-app-paths
  @cindex Umbrella Project
  This configuration is relevant for Erlang projects containing multiple OTP applications,
  also known as ``umbrella projects''.

  Application search path is a list of directories relative to the project root,
  where source code for an OTP application can be found.
  Template variable @code{$@{app@}} is substituted with the application name.

  The first directory in the list that contains @file{"src/$@{app@}.app.src"} file
  is selected as the application source root.

@end macro

@lee{anvl_erlc,ANVL Erlc}
